### ISSUE TITLE
Invalid windows path to Qt styles 

### ISSUE THREAD

**Issue by sohaibimran-10xe** [ihonen/qt-creator-themes#1]
So I wanted to add a style to my path and found that the path to the styles folder in the readme is not correct.

I was able to add style to the following path:
`C:\Qt\Tools\QtCreator\share\qtcreator\styles`

Of course `C:Qt`  is custom and varies depending on where user has installed Qt.

**Comment by ihonen** [comment]
It seems they have changed the path in one of the newer versions of Qt Creator – I haven't used it in a while. Thanks for the heads-up, I will update the instructions.
